services:
  postgres:
    image: postgres:17
    container_name: device-db
    healthcheck:
      test: ["CMD-SHELL", "psql -U local -d device -c \"SELECT 1\" || exit 1"]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - device-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: device

volumes:
  device-db-volume: