spring:
  application:
    name: servarium

  liquibase:
    change-log: classpath:db/changelog/main-changelog.yaml

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  jooq:
    sql-dialect: postgres

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

      max-lifetime: 1_200_000 # 20min
      connection-timeout: 15_000
      idle-timeout: 300_000 # 5min

      validation-timeout: 3_000

      leak-detection-threshold: 10_000
      auto-commit: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    display-request-duration: true
    filter: true
    operations-sorter: method